name: Publish

on:
  push: {}
  workflow_dispatch: {}

jobs:
  github-pages:
    name: Github Pages
    runs-on: ubuntu-22.04
    permissions:
        contents: read
        pages: write
        id-token: write
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    steps:
        - name: Check out source repository
          uses: actions/checkout@v2

        - uses: darklab8/fl-darkstat/.github/actions/build@master
          with:
            site-root: "/fl-data-discovery/"
            freelancer-folder: ${{ github.workspace }}
            heading: <a href="https://github.com/darklab8/fl-darkstat">fl-darkstat</a> for <a href="https://github.com/darklab8/fl-data-discovery">Freelancer Discovery</a>

        - uses: actions/upload-pages-artifact@v1
          with:
            name: github-pages
            path: ./build
        
        # Turn on ability to deploy to pages in repository settings, Pages tab
        # choose "Github Actions" deployment method to Pages
        - name: Deploy to pages
          uses: actions/deploy-pages@v1
          id: deployment
