name: Publish

on:
  push: {}

jobs:
  publish:
    uses: darklab8/fl-darkstat/.github/workflows/publish-to-pages.yml@master
    with:
      site-root: "/fl-data/"
      freelancer-folder: ${{ github.workspace }}
      heading: staging env for fl-darkstat <a href=\"https://github.com/darklab8/fl-darkstat\">Github</a>
